bg_images:
  widths: [600, 1000, 1500, 2000]
  min_width_difference: 30
  placeholder: false
  quality: 75
  lqip: #experimental 
    div: 1.5
    blur: 0
    quality: 20
    # jpg_quality: 70
    # webp_quality: 70
  lazy: false
  no_jpg: false 
  # hugo image processing options
  
  # site config only below
  root_margin: 25
  suppress_width_warning: false
